# Generated by Django 5.1.dev20240507180602 on 2024-06-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0005_alter_accountuser_account_user_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountuser",
            name="account_user_updated_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
