# Generated by Django 5.0.4 on 2024-06-14 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accountuser",
            options={"ordering": ("account_user_related_user",)},
        ),
        migrations.AlterField(
            model_name="accountuser",
            name="account_user_fullname",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="accountuser",
            name="account_user_related_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddIndex(
            model_name="accountuser",
            index=models.Index(
                fields=["account_user_id", "account_user_related_user"],
                name="apps_accoun_account_adaf6b_idx",
            ),
        ),
    ]
