# Generated by Django 5.0.4 on 2024-07-07 08:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0006_alter_accountuser_account_user_updated_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "course_id",
                    models.UUIDField(
                        default=uuid.UUID("53e4658b-5246-4f5e-aec0-10ad99ea7c1b"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("course_name", models.CharField(editable=False, max_length=255)),
                ("course_created_by", models.CharField(max_length=255)),
                ("course_created_date", models.DateTimeField(auto_now_add=True)),
                ("course_updated_by", models.CharField(max_length=255, null=True)),
                ("course_updated_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("course_id",),
                "indexes": [
                    models.Index(
                        fields=["course_id"], name="apps_course_course__5bf47f_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AttendingCourse",
            fields=[
                (
                    "attending_course_id",
                    models.UUIDField(
                        default=uuid.UUID("cd7079c1-1f72-436e-b45e-8d9c791f6880"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "attending_account_profile_id",
                    models.CharField(editable=False, max_length=255),
                ),
                ("attending_course_created_by", models.CharField(max_length=255)),
                (
                    "attending_course_created_date",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "attending_course_updated_by",
                    models.CharField(max_length=255, null=True),
                ),
                (
                    "attending_course_updated_date",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "attending_courseid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="apps.course"
                    ),
                ),
            ],
            options={
                "ordering": ("attending_course_id",),
                "indexes": [
                    models.Index(
                        fields=["attending_course_id", "attending_courseid"],
                        name="apps_attend_attendi_fcdc8c_idx",
                    )
                ],
            },
        ),
    ]
