# Generated by Django 5.1.dev20240507180602 on 2024-06-19 02:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0002_alter_accountuser_options_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="accountuser",
            new_name="apps_accoun_account_b45f73_idx",
            old_name="apps_accoun_account_adaf6b_idx",
        ),
        migrations.AlterField(
            model_name="accountuser",
            name="account_user_fullname",
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name="accountuser",
            name="account_user_id",
            field=models.UUIDField(
                default=uuid.UUID("4be33635-cd84-455c-ab26-9c572fa3c40f"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="accountuser",
            name="account_user_related_user",
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
