# Generated by Django 5.0.4 on 2024-07-14 07:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0007_course_attendingcourse"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendingcourse",
            name="attending_course_id",
            field=models.UUIDField(
                default=uuid.UUID("176a3418-8598-4e70-b12c-1e68a2ec8380"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="course_id",
            field=models.UUIDField(
                default=uuid.UUID("e896ce0a-165e-446b-b6a5-9b098cf3d40d"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
