# Generated by Django 5.0.4 on 2024-07-14 12:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0008_alter_attendingcourse_attending_course_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("username", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("street", models.CharField(blank=True, max_length=100, null=True)),
                ("suite", models.CharField(blank=True, max_length=100, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("zipcode", models.CharField(blank=True, max_length=20, null=True)),
                ("lat", models.CharField(blank=True, max_length=20, null=True)),
                ("lng", models.CharField(blank=True, max_length=20, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("website", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "catchPhrase",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("bs", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="attendingcourse",
            name="attending_course_id",
            field=models.UUIDField(
                default=uuid.UUID("ae5df0b6-04c3-4171-8340-a40ce3a5074e"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="course_id",
            field=models.UUIDField(
                default=uuid.UUID("1c43cf63-2b2b-44bb-9e3b-e7a4c990903f"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
