# Generated by Django 5.0.4 on 2024-06-19 02:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "apps",
            "0003_rename_apps_accoun_account_adaf6b_idx_apps_accoun_account_b45f73_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountuser",
            name="account_user_id",
            field=models.UUIDField(
                default=uuid.UUID("524b3910-f8f4-4f11-a7db-57363295edb4"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
